language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
env:
  global:
    secure: Vu7hHJuWkG88YKbZSNJOThrR49P66Jyybj4AQ3FMRdkO7yAzM8MPVp8FkxNVnkcoyLb21jL1H1J1U5EfcmZAb2L8rYdDHLsV0u2c2jrTgjMTqcsumU2pfLgeYT86cWVCE8JHGSpFMcbEUtADhGfmt4i3awIJYBULVlMoRHZJmJKE5POYlySqpRCvdnWhl5C+W/GF61qGDZFMeEDTpZhtivR6xA6ERmihagXZZiZ8JGH52LkS8EKsgg772nua6/BVX99wa5q6XiYtUiULBgUx40DZPk23h1wX60svHFNT7amskkoFFqoo95dXS0o3ZYRWvSjfFdCij2VtNHfabZs6KUBEtkYpTIlZ2/A3nDrIhI6FH/LQcP8uWuW0M/cY18/UljPCkJ6wi29WptdJn/vFmB7105DQgoEH1Q6WRtbOvJK0586afTvxk5cdbr4a9WUuxoopdwUtJiQGOXcAc1BQU4ZgwVRShf7r5bcFc3FNELY4yiUSR3/oMgrias7Pp2f4Qdi+vIVNEI66HB4Dhtu2bkrdPQg8Z0yoEesNrR2oNYdwcMPZXF06noRRmGKr8alQwHtDjvwtR/MlbVFzE18YX4jUK5IK2Wbj0bWglmUeujmXlXkowxdaIs1p61DA6ZJ3G90E3E+OcC4YYQTNE2BKFstzInqYjr2zT7XwCJ0MXCY=
